# Generated by Django 2.1 on 2018-08-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='clas',
        ),
        migrations.AddField(
            model_name='clas',
            name='teacher',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='unv.Teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='clas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='unv.Clas'),
            preserve_default=False,
        ),
    ]
